dynamic and responsive portfolio pages
klaudsol/klaudsol.com pull request #19
Opened 2022-03-24 10:32 UTC by hulyeen

2022-03-24 11:52 UTC, ardeearam commented on portfolio_content.json
> +
Better to move this into `/components` instead of putting this at the root directory, to keep things organized.

2022-03-24 11:53 UTC, ardeearam commented on components/about-us.js
> +import portfolio_content from "../portfolio_content.json";
Use absolute paths instead of relative paths.
```suggestion
import portfolio_content from "@/portfolio_content.json";
```

Or if you have moved it already
```suggestion
import portfolio_content from "@/components/portfolio_content.json";
```

2022-03-24 11:55 UTC, ardeearam commented on components/about-us.js
> +                            </p>
If we are using data from `portfolio-content.json`, why do we have Lorem Ipsum here still?

2022-03-24 11:55 UTC, ardeearam commented on components/about-us.js
> +              */}
Better remove code than commenting them out, for cleaner code.

2022-03-24 11:56 UTC, ardeearam commented on components/portfolio.js
> +                            <h3>Doorbell</h3>
Should this be for Sarisuki?

```suggestion
                            <h3>Sarisuki</h3>
```

2022-03-24 11:56 UTC, ardeearam commented on components/slider.js
> +                        */}
Remove code instead of commenting them out, for cleanliness.

2022-03-24 11:57 UTC, ardeearam commented on jsconfig.json
> +        "@/assets/*":["../assets/*"],
Do not use relative paths here.

```suggestion
        "@/assets/*":["public/assets/*"],
```

2022-03-24 11:58 UTC, ardeearam commented on next.config.js
> +module.exports = withImages()
Semicolons are still highly encouraged for readability.

```suggestion
const withImages = require('next-images');
module.exports = withImages();
```

2022-03-24 11:59 UTC, ardeearam commented on package.json
> +    "next-images": "^1.8.4",
Kindly update your code from `klaudsol:staging`, `next` should be on version `11.1.3`.

2022-03-24 11:59 UTC, ardeearam commented on pages/SarisukiPortfolio.js
> +import content from './content';
Use absolute paths instead of relative paths.

2022-03-24 11:59 UTC, ardeearam commented on pages/SarisukiPortfolio.js
> +import React from  'react';
Do we still need this page? If not, it's best to delete this file.

2022-03-24 12:01 UTC, ardeearam commented on pages/content.js
> +export default content;
Why do we have a content.js, and a portfolio_content.json?

Can we have just one content file?

2022-03-24 12:01 UTC, ardeearam commented on pages/portfolio/[id].js
> +import portfolio_content from "../../portfolio_content.json"
Avoid relative file paths please.

2022-03-24 12:02 UTC, ardeearam commented on pages/portfolio/[id].js
> +    <link href="../assets/css/plugin.css" rel="stylesheet" />
Relative paths don't work here. `/` starts at the `public` folder.

2022-03-24 12:02 UTC, ardeearam commented on pages/portfolio/[id].js
> +    <link href="../assets/css/style.css" rel="stylesheet" />
Relative paths don't work here. `/` starts at the `public` folder.

2022-03-24 12:02 UTC, ardeearam commented on pages/portfolio/[id].js
> +    <link href="../assets/css/responsive.css" rel="stylesheet" />
Relative paths don't work here. `/` starts at the `public` folder.

2022-03-24 12:03 UTC, ardeearam requested changes
Kindly see code comments.

Also, can you change the image of the girl to a screenshot of https://store.sarisuki.com?

2022-03-24 12:04 UTC, ardeearam commented
Also, kindly resolve merge conflicts.

2022-03-24 12:29 UTC, ardeearam commented on pages/content.js
> +    ]
Also, I don't think this file should be here. Files here should be React components, and are expected to be accessible via, for example, `/content` or `/portfolio/xxx`.

Better move this to the `/components` folder.

2022-03-24 13:05 UTC, hulyeen commented on components/slider.js
> +                        */}
this particular code is from the main branch po, may i stil remove it?

2022-03-24 13:23 UTC, hulyeen commented on pages/portfolio/[id].js
> +    <link href="../assets/css/plugin.css" rel="stylesheet" />
i have already tried this sir but the CSS is not reflecting on the page

2022-03-25 00:04 UTC, ardeearam commented on components/slider.js
> +                        */}
Yes please

2022-03-25 03:43 UTC, closed without merging