added technology stack section
klaudsol/klaudsol.com pull request #59
Opened 2022-04-01 03:38 UTC by hulyeen

2022-04-01 04:28 UTC, ardeearam commented on components/PortfolioContent.json
> +        "tech4": "Upstash Redis"
It would be more elegent if we make this into an array.

```suggestion
        "tech": ["Koa (Node.js)", "React", Shopify Polaris", "Upstash Redis"]
```

2022-04-01 04:28 UTC, ardeearam commented on components/PortfolioContent.json
> +        "tech4": "AWS Aurora Serverless"
https://github.com/klaudsol/klaudsol.com/pull/59/files#r840220828

2022-04-01 04:29 UTC, ardeearam commented on components/PortfolioContent.json
> +        "tech5": "Puppeteer"
https://github.com/klaudsol/klaudsol.com/pull/59/files#r840220828

2022-04-01 04:29 UTC, ardeearam commented on components/PortfolioContent.json
> +        "tech4": "AWS Aurora Serverless"
https://github.com/klaudsol/klaudsol.com/pull/59/files#r840220828

2022-04-01 04:30 UTC, ardeearam commented on pages/portfolio/[id].js
> +                      <p className="p1">WHAT WE DO</p>
This should be: `Technology Stack`
```suggestion
                      <p className="p1">Technology Stack</p>
```

2022-04-01 04:31 UTC, ardeearam commented on pages/portfolio/[id].js
> +                      <p className="p2">{p_content.tech5}</p>
It would be better if we iterate over all the items in the array.
```suggestion
                      {p_content.tech.map((tech) => (
                         <p className="p2">{tech}</p>    
                      )}                       
```

2022-04-01 04:32 UTC, ardeearam requested changes
Kindly see code review comments. Thanks!

2022-04-01 10:26 UTC, hulyeen commented on pages/portfolio/[id].js
> +                      <p className="p2">{p_content.tech5}</p>
noted, sir! nilagyan ko na rin po ng key prop

2022-04-02 08:10 UTC, ardeearam commented on pages/portfolio/[id].js
> +                        <p key = {tech.id}className='p2'>{tech}</p>
`tech` has no `id` property. I think pwede na ang `tech` itself as key.
```suggestion
                        <p key = {tech.id}className='p2'>{tech}</p>
```

2022-04-02 08:18 UTC, ardeearam approved these changes

2022-04-02 08:18 UTC, merged